### ISSUE TITLE
Sharing ToD's with Friends

### ISSUE THREAD

**Issue by jj0003** [jj0003/ToDoMate#2]
Sharing Capability: Implement a feature allowing users to share tasks with friends. This encourages collaboration and productivity among users.

My ToDos and My Mates' ToDos Tabs: Introduce two new tabs navigable by a secondary top bar, enabling users to toggle between their tasks and those shared by friends.

![Image](https://github.com/jj0003/ToDoMate/assets/93653402/e3f8c104-84a0-4876-965d-8087cc7675a9)

**Comment by B-Geltner** [comment]
uuuh das is geil

Jan Furio ***@***.***> schrieb am Di., 30. Apr. 2024, 23:23:
